# Generated by Django 2.0.1 on 2020-07-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_category_job'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
