# Generated by Django 2.0.1 on 2020-07-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200722_1954'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
